### PR TITLE
New structure for app modules

### LINKED ISSUE #103: Names for polymake apps
I have just encountered a problem with the polymake application names:

Polymake.jl currently exports application names, so we can access functions, e.g., `polytope.cube`. Unfortunately, Polymake.jl exports those without importing those names beforehand, because they are modules, so importing those names does not make sense. This leads to a confusion if you use Hecke and Polymake, because both currently export `ideal`, with a complete different meaning. And I assume that this might cause problems with other OSCAR components soonish. So what should we do?
* Not export them?
* Rename them into something like `app_ideal`
* . . .

Ideas highly appreaciated!

### PR DESCRIPTION
**Pull request by sebasguts**
* App modules do not get exported in module Polymake anymore
* App modules export their functions

Closes #103

### CODE REVIEW

**Comment by saschatimme** [comment]
I like that the modules export their functions but I somewhat disagree that the modules aren’t exported anymore. The problems in #103 only occur when you load both modules with `using`. It is good practice to only use import in library level code and the using in the REPL. If there are name collisions in the REPL then you have to distinguish them by specifying the prefix. But with not exporting the modules we are basically always ending with the fallback method.

**Comment by sebasguts** [comment]
Agreed that people should use `import` in their written code.

Normally I would agree that we should export it. The problem is that we cannot import `ideal`, because we create a new constant.

In the Julia world, how is it normally solved when two packages export the same name, without dependencies from each other? Would people simply be fine with the fact that they cannot write `using` for both? Or is there a way to define something like: "export, but only if not defined already"

**Comment by kalmarek** [comment]
the standard practice is that You export functions, and if user wish to use two modules with the same exported name they have to specify the module.

**Comment by sebasguts** [comment]
So they are forced to `import` the module instead of `using` it?

**Comment by saschatimme** [comment]
You can still call `using` you just have to specify the modules for all collisions.

More general if two Packages want to define methods for the same functions, then they should have a common dependency on some package which just defines these functions. Then both can export those. But if there is a clash between module names and functions then this doesn't help (but usually in Julia modules are capitalized, so this does not happen). There are plenty of packages in the Julia exosystem with the name *Base.jl which define some functions and some default capabilities. And then other packages can depend on this to extend the functionality.

**Comment by sebasguts** [comment]
This collision really only happens with modules, right? Types can have functions, too, right?

**Comment by saschatimme** [comment]
You mean I have a type `Polytope` and somebody has a module `Polytope`? I think there is some convention in pluralizing modules, i.e., the modules would be `Polytopes` and it exports a type `Polytope`.

**Comment by sebasguts** [comment]
No, I mean somebody has a `struct Polytope` and I have a function `Polytope`. That works I think. The problem is really just with modules.

**Comment by saschatimme** [comment]
You should only have capitalized functions for constructors.

**Comment by sebasguts** [comment]
But this is just a convention. Julia does not check this, so it is legal to do otherwise.

**Comment by kalmarek** [comment]
@sebasguts Your `Polytope` function will just add methods to the existing `Polytope` constructor (which may or may not return an instance of `Polytope`, damn be the users;-)

i.e. that would happen if You intend to *extend* someones `Polytope` function and import it first. If You don't, then these have to be specified i.e. `MyModule.Polytope(...)` (for your function), `SomeonesModule.Polytope(...)` (for a constructor of the struct)

**Comment by sebasguts** [comment]
Okay, I see. So we agree on still exporting the modules?

Should we still also export the functions from the modules, so one can `using Polymake.polytope`

**Comment by kalmarek** [comment]
I'm for exporting modules, but I feel ambiguous about exporting functions from modules;

As far as I understand in polymake shell You choose an application (which corresponds to `using Polymake; using Polymake.polytope;`) and then You have direct access to all functions from that application. You may still access the other functions by prepending the app name, e.g. 
```
polytope > $s = simplex(3); print $s;
Polymake::polytope::Polytope__Rational=ARRAY(0x5574c9765230)
polytope > $s2 = topaz::simplex(3); print $s2;
Polymake::topaz::SimplicialComplex=ARRAY(0x5574c9765620)
```
and this will correspond to:
```
using Polymake; using Polymake.polytope;
s = simplex(3) # polytopal simplex, since polytope.simplex was brought into main
s2 = topaz.simplex(3) # simplicial-complex
```

**Comment by kalmarek** [comment]
on the second thought, maybe we don't have to mimic polymake in this case?
but if we export all functions users will be faced with bunch of warnings when they `using Polymake`...?

**Comment by sebasguts** [comment]
In a sense we seem to already have agreed that when people type `using foo`, they need to know what they are doing. So if they get the warnings, the cannot make the two using statements.

**Comment by benlorenz** [comment]
In some way we are trying to please to different types of customers, those coming from a polymake background and those more familiar with julia. Maybe we should keep the corresponding names and exports somewhat separate:
We could rename our application modules according to julia standards, capitalized and some with plural: Common, Fans, Fulton, Graphs, Groups, Ideals, Matroids, Polytopes, Topaz and Tropical. These would be exported by default when 'using Polymake'.
Then we could add a second compatibility module (PolymakeCompat, PolymakeLingo, ...? Or is there some other way saying I want to load module X with feature Y?) for the polymake-users that exports the the lower case applications. We might also hide some of the more ugly hacks for polymake-style access to properties or functions there.

Also I think the applications should (in both variants) export their functions.

**Comment by sebasguts** [comment]
I like @benlorenz suggestion, and will implement it now :)

**Comment by kalmarek** [comment]
it went under my radar, i like the solution too

**Comment by sebasguts** [comment]
I updated the PR to contain the following

* Functions from the appmodules are exported
* Appmodules are now capitalized and pluralized, which is done by a list. If there is an app which is not in the list, the module will get created with the normal name, and the parser gives an error.
* There is a module `Polymake.PolymakeCompat` that can be used or imported. It contains the translations to the standard polymake app names.

**Comment by sebasguts** [comment]
For doing the `@pm` macro from #100 ? Indeed, that would be useful. I will autogenerate it in another PR, and make them actually included in the polymake module.

**Pull request merged**
