### PR TITLE
Bump version to v0.4.1

### PR DESCRIPTION
**Pull request by saschatimme**
I would really like to have a release with the Xcode 11.4 fix. Is there something holding this bacK?

### CODE REVIEW

**Comment by saschatimme** [comment]
Is the `Run tests / test (11.4, 0.9, macos-latest, 1.4` crash expected?

**Comment by benlorenz** [comment]
> Is the `Run tests / test (11.4, 0.9, macos-latest, 1.4` crash expected?

Somewhat expected, this is one of those random crashes with the old cxxwrap 0.9 and julia 1.4. It appears from time to time and might go away when you rerun the builds.

**Comment by saschatimme** [comment]
I see, then I will just accept this for now :)

**Comment by benlorenz** [comment]
@kalmarek wanted to do 0.4.1 in about one week as a replacement for the 0.4.0 but I guess we could also do another minor version in between.

**Comment by saschatimme** [comment]
In my opinion we should make patch releases as often as possible. I understand that we want to be conscious about minor releases but this is just an improvement for everybody.

Any thoughts @kalmarek

**Comment by kalmarek** [comment]
I'm fine releasing this now, minor minor versions are for bugfixes anyway

**Pull request merged**
