### PR TITLE
V0.3

### PR DESCRIPTION
**Pull request by kalmarek**
Updates README.md to the new syntax and bumps the version to `v0.3.0`

I added do not merge since it's better to 
- [x] merge @alexej-jordan types first and 
- [x] (maybe) get rid of all `pm_` prefixes
The last thing I'd definitely do it for `PerlObject`, `PropertyValue`, `OptionSet`), but `pm_Matrix` etc would have to be written as `Polymake.Matrix` etc, so people may have some opinions on this.
- [x] update to CxxWrap.jl 0.9.0
- [x] Fix options for visual #204 
- [x] Check and maybe bump binary dependencies (i.e. singularBuilder)

### CODE REVIEW

**Comment by saschatimme** [comment]
Merge?

**Comment by kalmarek** [comment]
I want to merge this just before tagging;
(docs i.e. README here still need to be updated for recent changes)

**Comment by saschatimme** [comment]
Then let me also add next week the `@convert_to` macro #189

**Comment by kalmarek** [comment]
I guess this is ready for merge, if tests pass

**Comment by saschatimme** [comment]
Didn't we want to have #213 in 0.3? (obviously we still can merge this now)

**Comment by alexej-jordan** [comment]
Currently working on some tests for #213, will push later this evening

**Comment by kalmarek** [comment]
yes, I want, but I want to merge this into master to announce `v0.3.0-rc1`;
I want to release `v0.3.0` on 21st of Feb

**Pull request merged**
