### PR TITLE
update notes on installation

### PR DESCRIPTION
**Pull request by kalmarek**

### CODE REVIEW

**Comment by kalmarek** [comment]
so how about registering `Polymake.jl` in the blessed global repo, so that `add url` can be replaced by `add Polymake` ? @saschatimme ?

**Comment by sebasguts** [comment]
How hard it is to get updates into that repo?

**Comment by kalmarek** [comment]
> How hard it is to get updates into that repo?

@saschatimme says You make a release on github which is automatically referenced a few hours later

**Comment by sebasguts** [comment]
So we should try to setup a travis that does releases for us? Or should we make them manually

**Pull request merged**
