### PR TITLE
Prepare initial release

### PR DESCRIPTION
**Pull request by saschatimme**
Changed version to `0.1.0` since we had no official release (or even a git tag) yet. So let's start at the beginning.

More todos:

- [x] Update binary builder polymake version to 3.4

### CODE REVIEW

**Comment by benlorenz** [comment]
As soon as [travis is done with boost](https://travis-ci.com/benlorenz/boostBuilder/builds/110106460) you can try merging my [bindeps/pm34 branch](https://github.com/benlorenz/Polymake.jl/tree/bindeps/pm34)

**Comment by kalmarek** [comment]
CI passes, but I have a local problem:
```
polymake:  ERROR: "/home/kalmar/.julia/dev/Polymake/deps/usr/share/polymake/perllib/Polymake/Core/CPlusPlus.pm", line 1799: Can't load shared module /home/kalmar/.julia/polymake_user/wrappers.1/build/Opt/lib/common.so: undefined symbol: pm::perl::ClassRegistratorBase::create_container_vtbl(std::type_info const&, unsigned long, int, int, void (*)(void*, char const*), void (*)(char*, sv*, pm::perl::ValueFlags), void (*)(char*), sv* (*)(char const*), sv* (*)(char const*, sv*), sv* (*)(), sv* (*)(), int (*)(char const*), void (*)(char*, int), void (*)(char*, char*, int, sv*), sv* (*)(), sv* (*)(), sv* (*)(), sv* (*)())
```
@benlorenz any idea?

**Comment by benlorenz** [comment]
> /home/kalmar/.julia/polymake_user/wrappers.1



> CI passes, but I have a local problem:
> 
> ```
> polymake:  ERROR: "/home/kalmar/.julia/dev/Polymake/deps/usr/share/polymake/perllib/Polymake/Core/CPlusPlus.pm", line 1799: Can't load shared module /home/kalmar/.julia/polymake_user/wrappers.1/build/Opt/lib/common.so: undefined symbol: pm::perl::ClassRegistratorBase::create_container_vtbl(std::type_info const&, unsigned long, int, int, void (*)(void*, char const*), void (*)(char*, sv*, pm::perl::ValueFlags), void (*)(char*), sv* (*)(char const*), sv* (*)(char const*, sv*), sv* (*)(), sv* (*)(), int (*)(char const*), void (*)(char*, int), void (*)(char*, char*, int, sv*), sv* (*)(), sv* (*)(), sv* (*)(), sv* (*)())
> ```
> 
> @benlorenz any idea?

Try removing `/home/kalmar/.julia/polymake_user/wrappers.1`.

**Comment by kalmarek** [comment]
@benlorenz yes it did worked;
Can we wipe the `polymake_user` directory every time we build?

**Comment by saschatimme** [comment]
I opened an issue #136 to keep track of this. For now let's get to a release.

**Pull request merged**
