### PR TITLE
Added helper to call methods/functions

### PR DESCRIPTION
**Pull request by sebasguts**
This is an alternative to #53 

Calling looks like
```
julia> c = Polymake.func.cube(3);

julia> Polymake.method.DIM(c)
3
```

### CODE REVIEW

**Comment by benlorenz** [comment]
When we make the functions available via this syntax I would prefer to have the functions directly under the application namespace and the methods could be grouped under the corresponding big object types:
```julia
julia> c = Polymake.polytope.cube(3);

julia> Polymake.polytope.Polytope.DIM(c)
3
```

**Comment by kalmarek** [comment]
`Polymake.polytope.Polytope.DIM(c)` is pretty horrible :-)
Not to mention that a user would expect the dimension function of a polytope to live in `Polymake.polytope` space

**Comment by sebasguts** [comment]
@benlorenz actually, this idea is not too bad. It looks horrible at first, but @kalmarek remember, you can still `using polytope` and then write `Polytope.DIM`

**Comment by benlorenz** [comment]
> `Polymake.polytope.Polytope.DIM(c)` is pretty horrible :-)
> Not to mention that a user would expect the dimension function of a polytope to live in `Polymake.polytope` space

We could also group them together under `.method` instead of separating them by object types since polymake will do the overload resolution anyway.

**Pull request closed without merging**
