### PR TITLE
Bump flint to 2.6.0

### PR DESCRIPTION
**Pull request by fingolfin**
This is based on `build_FLINT.v2.6.0.jl` from https://github.com/Nemocas/Nemo.jl/pull/849

One difference to that PR is that I didn't use `=0.3.0` for the LoadFlint version. I am happy to change it and add a comment explaining it, once somebody explains it to me first ;-)

### CODE REVIEW

**Comment by benlorenz** [comment]
I will need to prepare new polymake binaries for this to work, I will try do this later today.

**Comment by fingolfin** [comment]
@benlorenz OK thank you. And please take you time, no pressure was intended.  I just thought this would help, but I guess it's just the easy part :-/. Anyway, also feel free to close this and just take whatever bits help you (they are all stolen from @thofma anyway ;-)

**Comment by thofma** [comment]
I think I stole them from @benlorenz in the first place (from the LoadFlint repo).

**Comment by fingolfin** [comment]
This is obsolete now :-)

**Pull request closed without merging**
