### PR TITLE
Some bugfixes

### PR DESCRIPTION
**Pull request by sebasguts**
Some bugfixes in function.jl and convert.jl

### CODE REVIEW

**Comment by kalmarek** [comment]
we should have tests for indexing/converts into Matrices/Vectors
If I remember polymake is row-major, so converts are going to be inefficient.
 
@saschatimme how about linearindexing (so that we could `for i in eachindex`) them? worth the effort?

**Comment by saschatimme** [comment]
> If I remember polymake is row-major, so converts are going to be inefficient.
C/C++ is row major, so polymake as well :)

> How about linearindexing (so that we could for i in eachindex) them? worth the effort?
What effort? 
```julia
eachindex(A::AbstractArray) = (@_inline_meta(); eachindex(IndexStyle(A), A))
eachindex(::IndexLinear, A::AbstractArray) = (@_inline_meta; OneTo(length(A)))
eachindex(::IndexLinear, A::AbstractVector) = (@_inline_meta; axes1(A))
```
(btw you can find source code super easy with the `@less` macro, e.g. `A=rand(2,3);@less eachindex(A)`)

So we only need a  `getindex(A,i)` method and the `IndexStyle` trait.

But I am not sure whether doing row major iteration could not mess up generic code. E.g. you iterate over two matrices with linear indices, a Julia matrix and a Polymake matrix, this will be a mess.

**Comment by sebasguts** [comment]
@saschatimme I will add the tests tomorrow, it might be worth it if we change the syntax again some time soon. I would guess these bugfixes in convert were necessary because of the last change we did, so lets try to not break it again.

**Comment by kalmarek** [comment]
@saschatimme yeah, if You know exactly what to do, then no effort;)

and that's a good remark on joint iteration. I think it settles that row-major iteration is a bad idea;

**Comment by sebasguts** [comment]
@kalmarek @saschatimme I added the tests.

**Comment by kalmarek** [comment]
thanks!

**Pull request merged**
