### PR TITLE
choose fields when calling 'map' macro (polyDB)

### PR DESCRIPTION
**Pull request by alexej-jordan**
the user can now choose which fields are fetched from the database when querying using the macros. `_*` fields are added to the list. works with both `Polymake.BigObject` and `Mongoc.BSON`.

leaving the `_*` fields out for `Mongoc.BSON` appears inconvenient to me because this should probably not happen automatically (and if it should, when? iteration over a `Cursor{Mongoc.BSON}`? querying a `Collection{Mongoc.BSON}`?)

i should probably wait for the `documentation/new` branch to be merged so i can adjust the docstring for this macro, before we can merge this into the master.

### CODE REVIEW

**Comment by alexej-jordan** [comment]
macro is now working as intended and docstring is fitting.

this closes #314

**Comment by benlorenz** [comment]
Can we get one test for that feature?

**Comment by alexej-jordan** [comment]
is there already a way to check `Polymake.BigObject`'s property list? the `Polymake.exists(::Polymake.BigObject, ::String)` method might be enough to check, but is leaves us with a trade-off between precision and amount of code in this case.
the `list_properties` method would do, but it has (intentionally?) not been wrapped yet.

**Comment by benlorenz** [comment]
The `list_properties` method has not been wrapped explicitly but is still available via `call_method`:
```julia
julia> c = polytope.cube(3);

julia> x = Polymake.call_method(c,:list_properties)
6
```

Unfortunately our function call interface does not support list context at the moment (only void and scalar), so we cannot access the list but we do get the number of properties which should be sufficient for the test. Maybe in combination with `exists`.
(Perl automatically converts any array to its size when used in scalar context.)

**Pull request merged**
