### PR TITLE
add installation from `Project.toml`

### PR DESCRIPTION
**Pull request by kalmarek**

### CODE REVIEW

**Comment by kalmarek** [comment]
ok, it's not `Manifest.toml`, but `Project.toml`, but how do I change that, since the branch is protected?

**Comment by sebasguts** [comment]
I fixed this. But isn't it easier to do `add  <url>`?

**Comment by kalmarek** [comment]
I meant to add change in README.md, not the title of pull ;-)

`add url`  will add it to the global environment. 
`pull` + `activate` create a separate env, which you can safely delete, move afterwards

**Comment by sebasguts** [comment]
You should provide PR's from your own fork ;).

I would nevertheless vote for `add` as the default version. We can still keep this as a second option for people who want to have separate env's. I guess most people (like me 28 hours ago) do not even know they exist.

**Pull request closed without merging**
