### PR TITLE
bump to 0.4.3

### PR DESCRIPTION
**Pull request by kalmarek**
It should be possible to  call Registrator on this commit (not after the merge), am I right @saschatimme ?

### CODE REVIEW

**Comment by saschatimme** [comment]
Sure, you can call registrator on any commit, but the version number should be the correct one :)

**Comment by benlorenz** [comment]
We could also create a release_0_4 for this and bump master to 0.5 in preparation for the artifact stuff

**Comment by kalmarek** [comment]
@benlorenz yes, I thought about making this `0.4.3`, and then immediately changing master to `0.5-dev` or so.

**Comment by kalmarek** [comment]
julia-1.4 on MacOS fails on Set up Julia

**Comment by saschatimme** [comment]
I guess you just restarted the jobs?

**Comment by benlorenz** [comment]
I restarted them once.
But we could just close this without merging, that shouldn't affect the registration or tagging. And directly go to 0.5 on master.

**Comment by saschatimme** [comment]
I would suggest to merge this, register 0.4.3 and then branch from there a `releases/0.4` branch for eventual bugfixes.

**Comment by benlorenz** [comment]
I think @kalmarek wanted to have the polymake bump in 0.4.3 but not the polydb changes? In any case we should include #303 in the release.

**Comment by kalmarek** [comment]
@benlorenz that was my intention, but maybe let's not over-complicate things: I'll cherry-pick 58cd2e2 here and then we can tag

**Comment by benlorenz** [comment]
You can register directly on that cherry-picked commit and we can close this pull request without merging.

**Pull request closed without merging**
