### PR TITLE
Added example notebooks

### PR DESCRIPTION
**Pull request by IvanSpirandelli**

### CODE REVIEW

**Comment by kalmarek** [comment]
I had a look at those notebooks and they seem to be ok.
I would prefer a separate folder with `Project/Manifest.toml` fixing the environment.

**Comment by saschatimme** [comment]
Not related to this particular PR, but we should also update or delete the other example notebook.
(Or use something like [Literate.jl](https://github.com/fredrikekre/Literate.jl) to also integrate them into CI).

**Comment by kalmarek** [comment]
the other notebook is kept by @micjoswig here:
https://github.com/micjoswig/oscar-notebooks/blob/master/polymake/g-vectors_of_random_simplicial_6-polytopes.ipynb
@micjoswig maybe those notebooks created by @IvanSpirandelli should go there as well?

I like @saschatimme suggestion about using `Literate.jl` though

**Comment by benlorenz** [comment]
I would prefer to have them here in the Polymake.jl repository (or a new repo under oscar-system), and they should be tested automatically, see #268.

**Comment by IvanSpirandelli** [comment]
I added the tomls and created folders for the examples.

**Pull request closed without merging**
