### PR TITLE
Enh/rework conversion

### PR DESCRIPTION
**Pull request by kalmarek**
It still lacks test suite for arrays, vectors and matrices

based on `pm_Matrix{Float64}`

### CODE REVIEW

**Comment by saschatimme** [comment]
Does this is also handle the `compose(::Visual...)` stuff now?

**Comment by kalmarek** [comment]
Good point, I'll add this as well

**Comment by saschatimme** [comment]
Is this ready for review?

**Comment by sebasguts** [comment]
I get this error here

```
julia> x = [ Polymake.pm_Vector{Polymake.pm_Integer}([1]) ]
1-element Array{Polymake.pm_VectorAllocated{pm_Integer},1}:
 pm::Vector<pm::Integer>
1

julia> Polymake.convert_to_pm(x)
ERROR: StackOverflowError:
Stacktrace:
 [1] Type at ./boot.jl:402 [inlined]
 [2] Type at ./boot.jl:424 [inlined]
 [3] convert_to_pm(::Array{Polymake.pm_VectorAllocated{pm_Integer},1}) at ~.julia/dev/Polymake/src/convert.jl:54 (repeats 64968 times)
 [4] top-level scope at none:0
```

I will try and fix it first. Otherwise, this PR looks good to me.

**Comment by kalmarek** [comment]
I rebased onto the last master.

The one controversial decision I took was to make 
```julia
promote_type(::Type{Union{pm_Integer, pm_Rational}}, Type{<:AbstractFloat}) = Float64
```
this is to make `pm_Matrix([1 2;]) .+ 2.0` result in `pm_Matrix{Float64}`;
`Float64` constructors should be reasonably fast (computed on the C++ side, passed without boxing to julia).

Sorry for the size, but most of the additions are tests; 
@sebasguts, @saschatimme, it's yours

**Comment by saschatimme** [comment]
LGTM but can you also take a look @sebasguts ?

**Pull request merged**
