### PR TITLE
Fix/julia 1.5

### PR DESCRIPTION
**Pull request by kalmarek**
hopefully we will get all green here ;)

### CODE REVIEW

**Comment by saschatimme** [comment]
Can you replace the nightly job with `'^1.5.0-beta1'`?

**Comment by benlorenz** [comment]
There might be Julia version 1.5.0-beta1 available for github actions already (to test in addition to nightly):
https://github.com/julia-actions/setup-julia/commit/a81735fc3d28e542c32ea269e79de56397d8e2ee

**Comment by saschatimme** [comment]
Also can we cut down on some of the CI builds or are all still needed?

**Comment by kalmarek** [comment]
very well, should I add `1.5-beta1` or replace `nightly` ? are we cutting 1.3 of required?

Also: is the include array correct? julia versions there seem to be kind of random? (not that I understand what it does :)

**Comment by kalmarek** [comment]
mhm... all green...

**Comment by benlorenz** [comment]
I would prefer to keep nightly and 1.5, but we can definitely get rid of some julia 1.3 and cxxwrap 0.9 tests.

**Comment by saschatimme** [comment]
@benlorenz  I think Marek and I both don't have any strong preferences here. Do you want to push your preferred configuration on the branch?

**Comment by benlorenz** [comment]
ok, I can do that later today

**Comment by benlorenz** [comment]
done, and I adjusted the branch protection rules to match that.

**Comment by benlorenz** [comment]
Hm, this seems to be causing some warnings:
```
[ Info: Precompiling Polymake [d720cf60-89b5-51f5-aff5-213f193123e7]
WARNING: Method definition //(Polymake.Integer, Base.Rational{T} where T<:Integer) in module Polymake at /home/lorenz/software/polymake/julia/Polymake-extra.jl/src/rationals.jl:60 overwritten at /home/lorenz/software/polymake/julia/Polymake-extra.jl/src/rationals.jl:71.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition //(Base.Rational{T} where T<:Integer, Polymake.Integer) in module Polymake at /home/lorenz/software/polymake/julia/Polymake-extra.jl/src/rationals.jl:59 overwritten at /home/lorenz/software/polymake/julia/Polymake-extra.jl/src/rationals.jl:72.
  ** incremental compilation may be fatally broken for this module **
```
Can these be made fatal in the CI?

**Pull request merged**
